better github Action with support for multiple version, some small fixes

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,14 +1,16 @@
+# -*- fill-column: 120; -*-
+#
+# 1) package-lint run from Makefile (https://github.com/purcell/package-lint)
+# 2) leotaku/elisp-check
+
+---
 name: check
 
-run-name: "${{GITHUB_SHA}}"
+'on': [push, pull_request]
 
-on:
-  release:
-    types: [published]
-  pull_request:
-  push:
-    branches:
-      - master
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   check:
@@ -17,34 +19,85 @@ jobs:
       fail-fast: false
       matrix:
         emacs_version:
-          - 26.1
-          - 26.2
-          - 26.3
-          - 27.1
-          - 27.2
+          # - 26.1
+          # - 26.2
+          # - 26.3
+          # - 27.1
+          # - 27.2
           - 28.1
           - 28.2
           - 29.1
+          - 29.2
+          - 29.3
+          - 29.4
+          - 30.1
           - release-snapshot
-        ignore_warnings:
-          - true
+        experimental: [false]
         include:
           - emacs_version: snapshot
-            ignore_warnings: false
+            experimental: true
     steps:
-    - uses: actions/checkout@v3
-    - uses: purcell/setup-emacs@master
-      with:
-        version: ${{ matrix.emacs_version }}
-    - uses: leotaku/elisp-check@master
-      with:
-        file: '*-tests.el'
-        ignore_warnings: ${{ matrix.ignore_warnings }}
-        check: ert
-        warnings_as_errors: false
-    - uses: leotaku/elisp-check@master
-      with:
-        file: '*.el'
-        ignore_warnings: ${{ matrix.ignore_warnings }}
-        check: melpa
-        warnings_as_errors: false
+      - name: Install Emacs
+        uses: purcell/setup-emacs@master
+        with:
+          version: ${{ matrix.emacs_version }}
+
+      - name: Install Eask
+        uses: emacs-eask/setup-eask@master
+        with:
+          version: 'snapshot'
+
+      - name: Copy repo
+        uses: actions/checkout@v6
+
+      - uses: leotaku/elisp-check@master
+        with:
+          file: 'pinyin-isearch-chars.el'
+          check: melpa
+          ignore_warnings: false
+          warnings_as_errors: true
+      - uses: leotaku/elisp-check@master
+        with:
+          file: 'pinyin-isearch-pinyin.el'
+          check: melpa
+          ignore_warnings: false
+          warnings_as_errors: true
+      - uses: leotaku/elisp-check@master
+        with:
+          file: 'pinyin-isearch.el'
+          check: melpa
+          ignore_warnings: false
+          warnings_as_errors: true
+
+      - name: Run tests with eask and Make
+        run: |
+          make ci
+          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+        # |
+        #          echo $GITHUB_REF
+        # |& tee output.log
+
+
+      - name: Melpazoid check
+        env:
+          LOCAL_REPO: ${{ github.workspace }}
+          # RECIPE is your recipe as written for MELPA:
+          RECIPE: (pinyin-isearch :fetcher github :repo "Anoncheg1/pinyin-isearch")
+          # set this to false (or remove it) if the package isn't on MELPA:
+          EXIST_OK: true
+        run: |
+          echo $GITHUB_REF
+          make -C ~/melpazoid |& tee output.log
+          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          if grep -q "Warning" output.log ; then
+            echo "Warnings detected, failing workflow" ; exit 1
+          fi
+          if grep -q ': error: ' output.log ; then
+            echo "Error detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with checkdoc ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q 'much wider than 80 characters' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
+          fi
