fix github action

diff --git a/.github/workflows/melpazoid-release.yml b/.github/workflows/melpazoid-release.yml
--- a/.github/workflows/melpazoid-release.yml
+++ b/.github/workflows/melpazoid-release.yml
@@ -58,41 +58,36 @@ jobs:
         with:
           fetch-depth: 1
 
-      # - uses: leotaku/elisp-check@master
-      #   with:
-      #     file: 'pinyin-isearch-chars.el'
-      #     check: melpa
-      #     ignore_warnings: false
-      #     warnings_as_errors: true
-      # - uses: leotaku/elisp-check@master
-      #   with:
-      #     file: 'pinyin-isearch-pinyin.el'
-      #     check: melpa
-      #     ignore_warnings: false
-      #     warnings_as_errors: true
-      # - uses: leotaku/elisp-check@master
-      #   with:
-      #     file: 'pinyin-isearch.el'
-      #     check: melpa
-      #     ignore_warnings: false
-      #     warnings_as_errors: true
+      - name: Tests1
+        run: |
+         emacs -Q --batch --no-site-file -l pinyin-isearch-loaders.el -l pinyin-isearch-pinyin.el -l pinyin-isearch-pinyin-tests.el -f ert-run-tests-batch-and-exit
 
-      # - name: Run tests with eask and Make
-      #   run: |
-      #     make ci
-      #     [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
-      - name: Run CI
+      - name: Tests2
+        run: |
+         emacs -Q --batch --no-site-file -l pinyin-isearch-loaders.el -l pinyin-isearch-chars.el -l pinyin-isearch-chars-tests.el -f ert-run-tests-batch-and-exit
+
+      - name: Run Makefile
         run: |
           make test
           [ $? -ne 0 ] && { echo "Make test command failed, failing workflow"; exit 1; }
           make checkdoc
           [ $? -ne 0 ] && { echo "Make checkdoc command failed, failing workflow"; exit 1; }
-          make lint
-          [ $? -ne 0 ] && { echo "Make lint command failed, failing workflow"; exit 1; }
-        # |
-        #          echo $GITHUB_REF
-        # |& tee output.log
+          make lint |& tee output.log # always exit with 1 error code
+          if grep -q '[0-9] issue found:' output.log ; then
+            echo "Error detected, failing workflow" ; exit 1
+          fi
 
+      - name: Set up Python 3.12 for melpazoid
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.12
+
+      - name: Install melpazoid
+        run: |
+          python -m pip install --upgrade pip
+          # sudo apt-get install emacs-nox && emacs --version
+          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
+          pip install ~/melpazoid
 
       - name: Melpazoid check
         env:
@@ -104,16 +99,20 @@ jobs:
         run: |
           echo $GITHUB_REF
           make -C ~/melpazoid |& tee output.log
-          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          make_exit=${PIPESTATUS[0]}
+          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
           if grep -q ': error: ' output.log ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
-          if grep -q ' with checkdoc ' output.log ; then
+          if grep -q ' with [melpazoid]' output.log ; then
+            echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with package-lint ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
-          if grep -q 'much wider than 80 characters' output.log ; then
+          if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -26,17 +26,14 @@ jobs:
           # - 27.2
           - 28.1
           # - 28.2
-          # - 29.1
+          - 29.1
           # - 29.2
           # - 29.3
-          # - 29.4
+          - 29.4
           - 30.1
           - release-snapshot
     steps:
-      - name: Set up Python 3.12 for melpazoid
-        uses: actions/setup-python@v5
-        with:
-          python-version: 3.12
+
 
       # - name: Install
       #   run: |
@@ -68,7 +65,7 @@ jobs:
         run: |
          emacs -Q --batch --no-site-file -l pinyin-isearch-loaders.el -l pinyin-isearch-chars.el -l pinyin-isearch-chars-tests.el -f ert-run-tests-batch-and-exit
 
-      - name: Run CI
+      - name: Run Makefile
         run: |
           make test
           [ $? -ne 0 ] && { echo "Make test command failed, failing workflow"; exit 1; }
@@ -78,6 +75,18 @@ jobs:
           if grep -q '[0-9] issue found:' output.log ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
+
+      - name: Set up Python 3.12 for melpazoid
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.12
+
+      - name: Install melpazoid
+        run: |
+          python -m pip install --upgrade pip
+          # sudo apt-get install emacs-nox && emacs --version
+          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
+          pip install ~/melpazoid
 
       - name: Melpazoid check
         env:
@@ -89,7 +98,8 @@ jobs:
         run: |
           echo $GITHUB_REF
           make -C ~/melpazoid |& tee output.log
-          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          make_exit=${PIPESTATUS[0]}
+          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
