update Eask and try to suppress error about F1 key binding that is false-positive 5

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -9,6 +9,7 @@ name: melpazoid
 
 jobs:
   build:
+
     runs-on: ubuntu-latest
 
     timeout-minutes: 15
@@ -74,9 +75,8 @@ jobs:
           make checkdoc
           [ $? -ne 0 ] && { echo "Make checkdoc command failed, failing workflow"; exit 1; }
           make lint |& tee output.log # always exit with 1 error code
-          if grep -q '[0-9] issue found:' output.log ; then
-            echo GREP 10 lines ----------------------:
-            grep -A 10 '[0-9] issue found:' output.log
+          cat output.log | grep ': error: ' | grep -q -v "error: This key sequence is reserved"
+          if [ $? -eq 0 ] ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
 
@@ -107,8 +107,7 @@ jobs:
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
-          cat output.log | grep ': error: ' | grep -q -v "error: This key sequence is reserved"
-          if [ $? -eq 0 ] ; then
+          if grep -q ': error: ' output.log ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
           if grep -q ' with [melpazoid]' output.log ; then
