update Eask and try to suppress error about F1 key binding that is false-positive 14

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -102,19 +102,22 @@ jobs:
           EXIST_OK: true
         run: |
           echo $GITHUB_REF
-          make -C ~/melpazoid |& tee output.log
+          make -C ~/melpazoid 2>&1 | tee output.log
           make_exit=${PIPESTATUS[0]}
           # [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
-          if grep -q "Warning" output.log ; then
+          if grep "Warning" output.log | grep -q . ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
-          if grep ': error: ' output.log | grep -q -v "This key sequence is reserved"; then
+          if grep ' error: ' output.log | grep -v "This key sequence is reserved" | grep -q . ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
-          if grep -q ' with [melpazoid]' output.log ; then
+          if grep ' with [melpazoid]' output.log | grep -q . ; then
             echo "Melpazoid warning detected, failing workflow" ; exit 1
           fi
-          if grep -q ' with checkdoc ' output.log ; then
+           if grep ' with melpazoid' output.log | grep -q . ; then
+            echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep ' with checkdoc ' output.log | grep -q . ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
           echo "normal"
