better github Action with support for multiple version, some small fixes

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -1,30 +1,53 @@
+# -*- fill-column: 120; -*-
 # melpazoid <https://github.com/riscy/melpazoid> build checks.
 
 # If your package is on GitHub, enable melpazoid's checks by copying this file
 # to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.
-
+---
 name: melpazoid
-on: [push, pull_request]
+'on': [push, pull_request]
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python 3.12
-      uses: actions/setup-python@v1
-      with: { python-version: 3.12 }
-    - name: Install
-      run: |
-        python -m pip install --upgrade pip
-        sudo apt-get install emacs && emacs --version
-        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
-        pip install ~/melpazoid
-    - name: Run
-      env:
-        LOCAL_REPO: ${{ github.workspace }}
-        # RECIPE is your recipe as written for MELPA:
-        RECIPE: (pinyin-isearch :fetcher github :repo "Anoncheg1/pinyin-isearch")
-        # set this to false (or remove it) if the package isn't on MELPA:
-        # EXIST_OK: false
-      run: echo $GITHUB_REF && make -C ~/melpazoid
+      - name: Get repo to access in conteiner
+        uses: actions/checkout@v5
+        with:
+          fetch-depth: 0
+      - name: Set up Python 3.12
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.12
+      - name: Install
+        run: |
+          python -m pip install --upgrade pip
+          sudo apt-get install emacs-nox && emacs --version
+          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
+          pip install ~/melpazoid
+      # - name: Tests
+      #   run: |
+      #    emacs -Q --batch -l ert.el -l selected-window-contrast.el -l swc2-tests.el -f ert-run-tests-batch-and-exit
+      - name: Run
+        env:
+          LOCAL_REPO: ${{ github.workspace }}
+          # RECIPE is your recipe as written for MELPA:
+          RECIPE: (pinyin-isearch :fetcher github :repo "Anoncheg1/pinyin-isearch")
+          # set this to false (or remove it) if the package isn't on MELPA:
+          EXIST_OK: true
+        run: |
+          echo $GITHUB_REF
+          make -C ~/melpazoid |& tee output.log
+          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          if grep -q "Warning" output.log ; then
+            echo "Warnings detected, failing workflow" ; exit 1
+          fi
+          if grep -q ': error: ' output.log ; then
+            echo "Error detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with checkdoc ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q 'much wider than 80 characters' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
+          fi
