update Eask and try to suppress error about F1 key binding that is false-positive 3

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -108,15 +108,12 @@ jobs:
           if grep -q "Warning" output.log ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
-          if grep -q ': error: ' output.log ; then
+          cat output.log | grep ': error: ' | grep -q -v "error: This key sequence is reserved"
+          if [ $? -eq 0 ] ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
           if grep -q ' with [melpazoid]' output.log ; then
             echo "Melpazoid warning detected, failing workflow" ; exit 1
-          fi
-          cat output.log | grep error: | grep -v "error: This key sequence is reserved"
-          if [ $? -eq 0 ] ; then
-            echo "Error detected, failing workflow" ; exit 1
           fi
           if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
